apiVersion: v1
kind: Service
metadata:
  name: node-gke-cicd
  namespace: node-gke-cicd
  labels:
    app.kubernetes.io/name: node-gke-cicd
    app.kubernetes.io/part-of: node-gke-cicd
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: node-gke-cicd
  ports:
    - name: http
      port: 80
      targetPort: http

